apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-name-example-dm
  namespace: project-name-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-name-example
  template:
    metadata:
      name: server-name-example-pod
      labels:
        app: server-name-example
    spec:
      containers:
        - name: server-name-example
          # todo 修改私有仓库地址
          image: zhufuyi/project-name-example.server-name-example:latest
          # If using a local image, use Never, default is Always
          #imagePullPolicy: Never
          command: ["./serverNameExample", "-c", "/app/configs/serverNameExample.yml"]
          # todo 根据服务类型(http或grpc)选择端口
          ports:
            - name: http-port
              containerPort: 8080
            - name: grpc-port
              containerPort: 8282
            - name: metrics-port
              containerPort: 9082
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          volumeMounts:
            - name: server-name-example-vl
              mountPath: /app/configs/
              readOnly: true
          # todo 根据服务类型(http或grpc)选择健康检查
          # 就绪探测
          readinessProbe:
            httpGet:
              port: http-port
              path: /health
            #exec:
            #  command: ["/bin/grpc_health_probe", "-addr=:8282"]
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          # 容器存活探测
          livenessProbe:
            httpGet:
              port: http-port
              path: /health
            #exec:
            #  command: ["/bin/grpc_health_probe", "-addr=:8282"]
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      # todo 对于私有仓库，需要先创建Secret(这里名称docker-auth-secret)存放登录docker的账号和密码
      imagePullSecrets:
        - name: docker-auth-secret
      volumes:
        - name: server-name-example-vl
          configMap:
            name: server-name-example-config
