version: "3.7"

services:
  server-name-example:
    image: project-name-example.server-name-example:latest
    container_name: server-name-example
    restart: always
    command: ["./serverNameExample", "-c", "/app/configs/serverNameExample.yml"]
    volumes:
      - $PWD/configs:/app/configs
# todo generate docker-compose.yml code for http or grpc here
# delete the templates code start
    ports:
      - "8080:8080"   # http端口
      - "8282:8282"   # grpc服务端口
      - "8283:8283"   # grpc metrics端口
    # todo 根据服务类型(http或grpc)选择健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]   # http健康检查，注：镜像必须包含curl命令
      #test: ["CMD", "grpc_health_probe", "-addr=localhost:8282"]    # grpc健康检查，注：镜像必须包含grpc_health_probe命令
# delete the templates code end
      interval: 10s         # 间隔时间
      timeout: 5s           # 超时时间
      retries: 3              # 重试次数
      start_period: 10s  # 启动多久后开始检查
