name: Test and coverage

on:
  # 提交到main分支时触发执行jobs
  push:
    branches:
      - main
  # 合并到main分支时触发执行jobs
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /vendor/)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
