name: Go

on:
  # 提交到main分支时触发执行jobs
  push:
    branches:
      - main
  # 合并到main分支时触发执行jobs
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get dependencies
        run: go mod tidy
        env:
          GOPROXY: https://proxy.golang.org
      - name: Build
        run: go build -v cmd/serverNameExample/main.go
